name: Update RHDH Plugins

on:
    schedule:
        - cron: "0 2 * * *"
    workflow_dispatch:

jobs:
    update-plugins:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            packages: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - name: Generate GitHub App token
              id: app-token
              uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
              with:
                  app-id: ${{ secrets.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - name: Update plugins for next__ and bs_ tags
              uses: redhat-ai-dev/rhdh-plugin-gitops-updater@2f9907ebb01539c6f344893f2be603e770b93b68 # v1.0.8
              with:
                  config-path: "charts/rhdh/values.yaml"
                  github-token: ${{ steps.app-token.outputs.token }}
                  base-branch: development
                  tag-prefixes: |
                      next__
                      bs_
                  update-pr-strategy: "separate"
                  verbose: "1"
